[versions]
minecraft = "1.19.3"
quilt_mappings = "1.19.3+build.23"
fabric_loader = "0.14.14"

fabric_api = "0.73.2+1.19.3"
sodium = "mc1.19.3-0.4.9"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
sodium = { module = "maven.modrinth:sodium", version.ref = "sodium" }

[plugins]
fabric_loom = { id = "fabric-loom", version = "1.1.+" }
loom_quiltflower = { id = "io.github.juuxel.loom-quiltflower", version = "1.8.+" }
grgit = { id = "org.ajoberstar.grgit", version = "5.+" }
